service:
  info:
    secured: true
    truststore:
      path: ./client-feign/src/main/resources/infocert.p12
      alias: info
      password: changeit
    connectionTimeout: 500
    readTimeout: 500
    retries: 5
    paths: localhost:8080,localhost:8081
  status:
    secured: true
    truststore:
      path: ./client-feign/src/main/resources/statuscert.p12
      alias: status
      password: changeit
    connectionTimeout: 100
    readTimeout: 100
    retries: 3
    paths: localhost:8082,localhost:8083